import type { Metadata } from "next";
import "./globals.css";

import FacebookPixel from "@/components/FacebookPixel";
import PageViewTracker from "@/components/PageViewTracker";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <FacebookPixel />
        <PageViewTracker/>
        {children}
      </body>
    </html>
  );
}









// import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
// import './globals.css';
// import dynamic from 'next/dynamic';
// const FacebookPixel = dynamic(import('../components/FacebookPixel'));

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin']
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin']
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

// export default function RootLayout({
//   children
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <FacebookPixel />
//         {children}
//       </body>
//     </html>
//   );
// }
